version: "3.1"
services:

  nginx:
    image: nginx:1.13.7-alpine
    container_name: rt-nginx
    working_dir: /rt
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/ssl
      - .:/rt
      - ./data/logs/nginx:/var/log/nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - rt_net
    links:
      - "php-fpm:php-fpm"

  php-fpm:
    build: ./docker/php-fpm
    container_name: rt_php-fpm
    working_dir: /rt
    volumes:
      - ./docker/php-fpm/php-overwrite.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-gsc-fpm.conf
      - ./data/logs/php:/var/log
      - .:/rt
    restart: always
    ports:
      - "9000:9000"
    networks:
      - rt_net
    links:
      - "mysql:database"

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "db_rt"
      MYSQL_USER: "user_rt"
      MYSQL_PASSWORD: "123456789"
    container_name: rt-mysql
    working_dir: /rt
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/data
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./reports:/reports
      - mysql_data:/var/lib/mysql
      - ./data/logs/mysql:/var/log/mysql
    networks:
      - rt_net


volumes:
  mysql_data:


networks:
  rt_net: